---
- name: do some prechecks
  import_tasks: prechecks.yml

- name: set directory
  set_fact:
    local_host_directory: "{{ git_repo_path }}/{{ inventory_hostname }}" 

- name: create directory for host {{ inventory_hostname }}
  file: 
    path: "{{ local_host_directory }}"
    state: directory
  delegate_to: localhost
  become: false


- name: check on users
  import_tasks: user_check.yml

- name: check JAVA version
  import_tasks: java_version.yml

- name: check active listening ports
  import_tasks: listening_ports.yml





- name: timestamp log
  command: "mv ansible.log run-{{ ansible_date_time.date }}-{{ansible_date_time.time }}.log"
  args:
    chdir: "{{ playbook_dir }}/logs"
  become: false
  delegate_to: localhost
  run_once: true
  changed_when: false

- import_tasks: git.yml
