
# changed_when: false because we are executing command
# we want to reserve the changed event for file changes for better detection
- name: print users
  command: cat /etc/passwd
  register: etc_passwd
  changed_when: false

# copy is idempotent
- name: write /etc/passwd to file 
  import_tasks: write-to-file.yml
  vars: 
    file_name: passwd
    file_content: "{{ etc_passwd.stdout }}"
